//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO_QLBanHang
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QLBanHangEntities : DbContext
    {
        public QLBanHangEntities()
            : base("name=QLBanHangEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Hang> Hangs { get; set; }
        public virtual DbSet<Khach> Khaches { get; set; }
        public virtual DbSet<NhanVien> NhanViens { get; set; }
    
        public virtual ObjectResult<Nullable<int>> sp_InsertNhanVien(string email, string tenNV, string diaChi, Nullable<byte> vaiTro, Nullable<byte> tinhTrang, string matKhau)
        {
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var tenNVParameter = tenNV != null ?
                new ObjectParameter("tenNV", tenNV) :
                new ObjectParameter("tenNV", typeof(string));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("diaChi", diaChi) :
                new ObjectParameter("diaChi", typeof(string));
    
            var vaiTroParameter = vaiTro.HasValue ?
                new ObjectParameter("vaiTro", vaiTro) :
                new ObjectParameter("vaiTro", typeof(byte));
    
            var tinhTrangParameter = tinhTrang.HasValue ?
                new ObjectParameter("tinhTrang", tinhTrang) :
                new ObjectParameter("tinhTrang", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_InsertNhanVien", emailParameter, tenNVParameter, diaChiParameter, vaiTroParameter, tinhTrangParameter);
        }
    }
}
